// Full macro indicator registry (83 keys, 8 categories) — snapshot of the live
// macro DB (2026-06-03), from docs/macro-indicators.md. These are the valid
// `macro` operand keys the agent may use and the FE data-point chips show.
export const MACRO_KEYS = [
  // ── business (20) ──
  { key: 'capacity_utilization', name: 'Capacity Utilization', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'chicago_pmi', name: 'Chicago PMI', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'core_durable_goods', name: 'Core Durable Goods Orders', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'durable_goods_orders', name: 'Durable Goods Orders', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'factory_orders_mm', name: 'Factory Orders (MoM)', category: 'business', frequency: 'monthly' },
  { key: 'industrial_production_mm', name: 'Industrial Production (MoM)', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'ism_manufacturing_pmi', name: 'ISM Manufacturing PMI', category: 'business', frequency: 'monthly' },
  { key: 'ism_mfg_prices', name: 'ISM Manufacturing Prices', category: 'business', frequency: 'monthly' },
  { key: 'ism_non_mfg_prices', name: 'ISM Non-Manufacturing Prices', category: 'business', frequency: 'monthly' },
  { key: 'ism_services_pmi', name: 'ISM Services PMI', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'ny_empire_state', name: 'NY Empire State Manufacturing Index', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'philadelphia_fed', name: 'Philadelphia Fed Manufacturing Index', category: 'business', frequency: 'monthly' },
  { key: 'richmond_fed', name: 'Richmond Fed Manufacturing Index', category: 'business', frequency: 'monthly' },
  { key: 'sp_global_composite_pmi', name: 'S&P Global Composite PMI', category: 'business', frequency: 'monthly' },
  { key: 'sp_global_mfg_pmi', name: 'S&P Global Manufacturing PMI', category: 'business', frequency: 'monthly' },
  { key: 'sp_global_services_pmi', name: 'S&P Global Services PMI', category: 'business', frequency: 'monthly' },
  { key: 'total_vehicle_sales', name: 'Total Vehicle Sales', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'wholesale_inventories', name: 'Wholesale Inventories', category: 'business', frequency: 'monthly', unit: '%' },
  { key: 'durable_goods_ex_defense', name: 'Durable Goods Orders ex Defense', category: 'business', frequency: 'quarterly' },
  { key: 'industrial_production_yy', name: 'Industrial Production (YoY)', category: 'business', frequency: 'quarterly', unit: '%' },
  // ── consumer (8) ──
  { key: 'consumer_confidence', name: 'Consumer Confidence', category: 'consumer', frequency: 'monthly' },
  { key: 'consumer_spending', name: 'Consumer Spending', category: 'consumer', frequency: 'monthly', unit: '%' },
  { key: 'core_retail_sales_mm', name: 'Core Retail Sales (MoM)', category: 'consumer', frequency: 'monthly', unit: '%' },
  { key: 'michigan_consumer_expectations', name: 'Michigan Consumer Expectations', category: 'consumer', frequency: 'monthly', unit: '%' },
  { key: 'personal_income_mm', name: 'Personal Income (MoM)', category: 'consumer', frequency: 'monthly', unit: '%' },
  { key: 'personal_spending_mm', name: 'Personal Spending (MoM)', category: 'consumer', frequency: 'monthly', unit: '%' },
  { key: 'retail_sales_mm', name: 'Retail Sales (MoM)', category: 'consumer', frequency: 'monthly', unit: '%' },
  { key: 'retail_sales_yy', name: 'Retail Sales (YoY)', category: 'consumer', frequency: 'quarterly', unit: '%' },
  // ── gdp (6) ──
  { key: 'gdp_qoq_final', name: 'GDP QoQ Final', category: 'gdp', frequency: 'monthly', unit: '%' },
  { key: 'gdp_yoy_final', name: 'GDP YoY Final', category: 'gdp', frequency: 'monthly', unit: '%' },
  { key: 'gdp_qoq_adv', name: 'GDP QoQ Advance', category: 'gdp', frequency: 'quarterly', unit: '%' },
  { key: 'gdp_qoq_prelim', name: 'GDP QoQ Preliminary', category: 'gdp', frequency: 'quarterly', unit: '%' },
  { key: 'gdp_yoy_adv', name: 'GDP YoY Advance', category: 'gdp', frequency: 'quarterly', unit: '%' },
  { key: 'gdp_yoy_prelim', name: 'GDP YoY Preliminary', category: 'gdp', frequency: 'quarterly', unit: '%' },
  // ── government (2) ──
  { key: 'debt_to_gdp', name: 'Debt to GDP', category: 'government', frequency: 'monthly', unit: '%' },
  { key: 'government_debt', name: 'Government Debt', category: 'government', frequency: 'monthly' },
  // ── housing (16) ──
  { key: 'building_permits', name: 'Building Permits', category: 'housing', frequency: 'monthly' },
  { key: 'case_shiller_mm', name: 'Case-Shiller Home Price Index (MoM)', category: 'housing', frequency: 'monthly', unit: '%' },
  { key: 'construction_spending', name: 'Construction Spending', category: 'housing', frequency: 'monthly' },
  { key: 'existing_home_sales', name: 'Existing Home Sales', category: 'housing', frequency: 'monthly' },
  { key: 'housing_starts', name: 'Housing Starts', category: 'housing', frequency: 'monthly' },
  { key: 'mortgage_applications', name: 'Mortgage Applications', category: 'housing', frequency: 'monthly' },
  { key: 'nahb_hmi', name: 'NAHB Housing Market Index', category: 'housing', frequency: 'monthly', unit: '%' },
  { key: 'new_home_sales', name: 'New Home Sales', category: 'housing', frequency: 'monthly' },
  { key: 'new_home_sales_mm', name: 'New Home Sales (MoM)', category: 'housing', frequency: 'monthly' },
  { key: 'pending_home_sales_mm', name: 'Pending Home Sales (MoM)', category: 'housing', frequency: 'monthly' },
  { key: 'pending_home_sales_yy', name: 'Pending Home Sales (YoY)', category: 'housing', frequency: 'monthly', unit: '%' },
  { key: 'building_permits_mm', name: 'Building Permits (MoM)', category: 'housing', frequency: 'quarterly' },
  { key: 'case_shiller_yy', name: 'Case-Shiller Home Price Index (YoY)', category: 'housing', frequency: 'quarterly', unit: '%' },
  { key: 'existing_home_sales_mm', name: 'Existing Home Sales (MoM)', category: 'housing', frequency: 'quarterly' },
  { key: 'housing_starts_mm', name: 'Housing Starts (MoM)', category: 'housing', frequency: 'quarterly', unit: '%' },
  { key: 'mortgage_rate', name: '30-Year Mortgage Rate', category: 'housing', frequency: 'weekly' },
  // ── inflation (17) ──
  { key: 'core_cpi_mm', name: 'Core CPI (MoM)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'core_cpi_yy', name: 'Core CPI (YoY)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'core_pce_yy', name: 'Core PCE (YoY)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'core_pce_yy_1', name: 'Core PCE (YoY) Alt', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'core_ppi_mm', name: 'Core PPI (MoM)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'cpi_mm', name: 'CPI (MoM)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'cpi_yy', name: 'CPI (YoY)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'export_prices_mm', name: 'Export Prices (MoM)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'import_prices_mm', name: 'Import Prices (MoM)', category: 'inflation', frequency: 'monthly' },
  { key: 'import_prices_yy', name: 'Import Prices (YoY)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'inflation_expectations', name: 'Inflation Expectations', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'pce_mm', name: 'PCE (MoM)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'pce_yy', name: 'PCE (YoY)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'ppi_mm', name: 'PPI (MoM)', category: 'inflation', frequency: 'monthly', unit: '%' },
  { key: 'ppi_yy', name: 'PPI (YoY)', category: 'inflation', frequency: 'monthly' },
  { key: 'core_ppi_yy', name: 'Core PPI (YoY)', category: 'inflation', frequency: 'quarterly', unit: '%' },
  { key: 'export_prices_yy', name: 'Export Prices (YoY)', category: 'inflation', frequency: 'quarterly' },
  // ── labor_market (12) ──
  { key: 'adp_employment', name: 'ADP Employment Change', category: 'labor_market', frequency: 'monthly' },
  { key: 'avg_hourly_earnings_mm', name: 'Average Hourly Earnings (MoM)', category: 'labor_market', frequency: 'monthly', unit: '%' },
  { key: 'continuing_jobless_claims', name: 'Continuing Jobless Claims', category: 'labor_market', frequency: 'monthly', unit: '%' },
  { key: 'employment_cost_index', name: 'Employment Cost Index', category: 'labor_market', frequency: 'monthly', unit: '%' },
  { key: 'initial_jobless_claims', name: 'Initial Jobless Claims', category: 'labor_market', frequency: 'monthly', unit: 'K' },
  { key: 'jolts_job_openings', name: 'JOLTS Job Openings', category: 'labor_market', frequency: 'monthly', unit: 'M' },
  { key: 'jolts_quit_rate', name: 'JOLTS Quit Rate', category: 'labor_market', frequency: 'monthly', unit: '%' },
  { key: 'nfp', name: 'Non-Farm Payrolls', category: 'labor_market', frequency: 'monthly', unit: 'K' },
  { key: 'unemployment_rate', name: 'Unemployment Rate', category: 'labor_market', frequency: 'monthly', unit: '%' },
  { key: 'avg_hourly_earnings_yy', name: 'Average Hourly Earnings (YoY)', category: 'labor_market', frequency: 'quarterly', unit: '%' },
  { key: 'participation_rate', name: 'Labor Force Participation Rate', category: 'labor_market', frequency: 'quarterly', unit: '%' },
  { key: 'avg_work_week', name: 'Average Work Week', category: 'labor_market', frequency: 'weekly' },
  // ── money (2) ──
  { key: 'fed_balance_sheet', name: 'Fed Balance Sheet', category: 'money', frequency: 'monthly' },
  { key: 'interest_rate', name: 'Fed Funds Rate', category: 'money', frequency: 'monthly', unit: '%' },
];
